config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  default_url_options host: 'localhost:3000'

  get '/contact', to: 'messages#contact'

  resources :record_libraries
  resources :friendships
  root 'albums#index'

  get 'sessions/new'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :messages, only: %i[new create]

  get 'admin/dashboard' => 'admin#index'
  # The namespace  creates a nested url for admin panel check rake routes for details
  namespace :admin do
    get 'categories/new' => 'categories#new_category'
    resources :categories, only: %i[index create edit update delete]

    get 'artists/new' => 'artists#new_artist'
    get 'artists' => 'artists#index_artist'
    get 'artists/:id/edit' => 'artists#edit_artist', as: 'artists_edit'
    resources :artists, only: %i[create update destroy]

    get 'albums/new' => 'albums#new_album'
    get 'albums' => 'albums#index_album'
    get 'albums/:id/edit' => 'albums#edit_album', as: 'albums_edit'
    resources :albums, only: %i[create update destroy]

    resources :photos
    get 'songs/new' => 'songs#new_song'
    get 'songs' => 'songs#index_song'
    get 'songs/:id/edit' => 'songs#edit_song', as: 'songs_edit'
    resources :songs, only: %i[index create edit update destroy]

    get 'bands/new' => 'bands#new_band'
    get 'bands' => 'bands#index_band'
    get 'bands/:id/edit' => 'bands#edit_band', as: 'bands_edit'
    resources :bands, only: %i[index create edit update destroy]

    get 'users/new' => 'users#new_user'
    get 'users' => 'users#index_user'
    get 'user/:id/edit' => 'users#user_edit', as: 'user_edit'
    resources :users, only: %i[create update destroy]
  end

  resources :bands
  resources :artists
  resources :recommendations, only: %i[index]
  get 'album/:id' => 'albums#show', as: 'album'

  # mailboxer
  resources :conversations, only: %i[index show destroy create] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
    member do
      post :mark_as_read
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  get 'categories' => 'categories#index'
  resources :categories
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums, dependent: :nullify
  has_many :bandmembers, dependent: :destroy
  has_many :photos, as: :imageable, dependent: :destroy
  has_many :bands, through: :bandmembers
  belongs_to :category, optional: true

  validates :name, presence: true
  validates :description, presence: true
  validates :country, presence: true
  validates :category_id, presence: true
  validates :photos, presence: true
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < AdminController
  before_action :require_admin
  before_action :find_artist, only: %i[update delete]

  def index_artist
    @artists = Artist.includes([bandmembers: :band], [:category])
  end

  def new_artist
    @artist = Artist.new
    @artists = Artist.all.map { |b| [b.name, b.id] }
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      if params[:images]
        params[:images].each do |image|
          @artist.photos.create(image: image)
        end
      else
        @artist.photos.create
      end
      flash[:success] = "Artist #{@artist.name} is created"
      redirect_to admin_artists_path
    else
      flash[:warning] = 'Please try again'
      action admin_artist_new_path
    end
  end

  def edit_artist
    @artist = Artist.find(params[:id])
  end

  def update; end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to admin_artists_path
  end

  private

  def find_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    # ,:category_id,
    params.require(:artist).permit(:name, :country, :category_id, :description, :photos)
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def show
    @artist = Artist.find(params[:id])
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def artists_for_select
    Artist.all.collect { |u| [u.name.to_s, u.id] }
  end

  def song_artist(song)
    name = Artist.find(song.artist_id).name unless song.artist_id.nil?
    name.to_s
  end
end

app/views/artists/_artist_row.html.erb
<tr>
  <td><%= artist.name %></td>
  <td><%= artist.category.name %></td>
  <td><%= band.name %></td>
  <td>
    <%= link_to admin_artists_edit_path(artist),class: "btn btn-primary btn-xs pull-right" do %>
      <span class="glyphicon glyphicon-edit"></span>Edit</button>
  <%end%>
  <%= link_to admin_artist_path(artist),method: :delete, data: {confirm: 'Are you sure?'},class: "btn btn-danger btn-xs pull-right" do %>
    <span class="glyphicon glyphicon-remove-circle"></span> Delete</button>
<%end%>
</td>
</tr>

app/views/artists/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <ol class="breadcrumb">
        <li class="active">
          <i class="fa fa-dashboard"></i> Album
        </li>
      </ol>
      <%= render 'admin/flash_messages'%>
      <div class="panel panel-default">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Category/Genre</th>
              <th>Artist/Band</th>
              <th><%= link_to "New" , admin_artists_new_path, class: "pull-right btn btn-success btn-md"%></th>
            </tr>
          </thead>
          <tbody>
            <%@artists.each do |artist|%>
              <% artist.bandmembers.each do |bandmember| %>
                <%= render 'artists/artist_row', artist: artist,band: bandmember.band%>
              <%end%>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/artists/_new.html.erb
<%= render partial: 'admin/admin_dash_nav'%>
<div id="page-wrapper">
  <div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Dashboard <small>New Artist</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <i class="fa fa-dashboard"></i> Artist
          </li>
        </ol>
        <%= render 'admin/flash_messages'%>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= form_for [:admin , @artist],:html => { :multipart => true } do |f| %>
          <% if @artist.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@artist.errors.count, "error") %> prohibited
                this seminars from being saved:
              </h2>
              <ul>
                <% @artist.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="inputName"  class='pull-left'>Name</label>
            <%= f.text_field :name, class: "form-control",id: 'inputName' , :required => true %>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label for="inputdescription" class='pull-left'>Description</label>
            <%= f.text_field :description, class: "form-control",id: "inputdescription", :required => true%>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label for="inputCountry" class='pull-left'>Country</label>
            <%= f.label :country, class: 'pull-left'%>
            <%= f.text_field :country, class: "form-control",id: 'inputCountry', :required => true %>
          </div>
          <div class="form-group">
            <label for="category">Category/Genre</label>
            <%= f.select(:category_id, deep_categories_for_select, {include_blank:true , include_hidden:false} ,id: 'category' , class: 'select2 form-control', :required => true)%>
            <div class="help-block with-errors"></div>
          </div>
          <% if @artist.photos.exists? %>
            <% @artist.photos.each do |z| %>
              <div class="seminarimage">
                <% if !z.image_file_size.nil? %>
                  <%= image_tag z.image , class: "showimage" %>
                  <%= link_to "Delete Photo",admin_photo_path(z), :method => :delete  , remote: true , class: "photo_delete"%>
                <%else%>
                  <p>
                    Προσθέστε μια φωτογραφία
                  </p>
                <%end%>
              </div>
            <%end%>
          <%end%>
          <div class="control-group">
            <%= f.label :photos, :class => 'control-label' %>
            <div class="form-group">
              <%= file_field_tag "images[]", type: :file, multiple: true ,class: "form-control-file" %>
            </div>
          </div>
          <p>
            <%= f.submit nil , class: 'btn btn-primary' %>
          </p>
        <% end %>
        <%= link_to 'Back', admin_dashboard_path %>
      </div>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
<div class ="container">
  <div class="row">
    <div class="col-md-12">
      <% @artist.photos.each do  |photo|%>
        <%=image_tag  photo.image ,class:'imagesize-artist-show'%>
      <%end%>
    </div>
  </div>
  <div clas = "row">
    <div class="col-md-4">
      <%=@artist.name%>
    </div>
    <div class="col-md-4">
      <%=@artist.description%>
    </div>
  </div>
</div>