config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  default_url_options host: 'localhost:3000'

  get '/contact', to: 'messages#contact'

  resources :record_libraries
  resources :friendships
  root 'albums#index'

  get 'sessions/new'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :messages, only: %i[new create]

  get 'admin/dashboard' => 'admin#index'
  # The namespace  creates a nested url for admin panel check rake routes for details
  namespace :admin do
    get 'categories/new' => 'categories#new_category'
    resources :categories, only: %i[index create edit update delete]

    get 'artists/new' => 'artists#new_artist'
    get 'artists' => 'artists#index_artist'
    get 'artists/:id/edit' => 'artists#edit_artist', as: 'artists_edit'
    resources :artists, only: %i[create update destroy]

    get 'albums/new' => 'albums#new_album'
    get 'albums' => 'albums#index_album'
    get 'albums/:id/edit' => 'albums#edit_album', as: 'albums_edit'
    resources :albums, only: %i[create update destroy]

    resources :photos
    get 'songs/new' => 'songs#new_song'
    get 'songs' => 'songs#index_song'
    get 'songs/:id/edit' => 'songs#edit_song', as: 'songs_edit'
    resources :songs, only: %i[index create edit update destroy]

    get 'bands/new' => 'bands#new_band'
    get 'bands' => 'bands#index_band'
    get 'bands/:id/edit' => 'bands#edit_band', as: 'bands_edit'
    resources :bands, only: %i[index create edit update destroy]

    get 'users/new' => 'users#new_user'
    get 'users' => 'users#index_user'
    get 'user/:id/edit' => 'users#user_edit', as: 'user_edit'
    resources :users, only: %i[create update destroy]
  end

  resources :bands
  resources :artists
  resources :recommendations, only: %i[index]
  get 'album/:id' => 'albums#show', as: 'album'

  # mailboxer
  resources :conversations, only: %i[index show destroy create] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
    member do
      post :mark_as_read
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  get 'categories' => 'categories#index'
  resources :categories
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: %i[index empty_trash]
  before_action :get_box, only: [:index]

  def index
    @conversations = if @box.eql? 'inbox'
                       @mailbox.inbox
                     elsif @box.eql? 'sent'
                       @mailbox.sentbox
                     else
                       @mailbox.trash
                     end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_box
    if params[:box].blank? || !%w[inbox sent trash].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def show; end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
 end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>
  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                  class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
    <% end %>
  </div>
  <p><%= render 'conversations/participants', conversation: conversation %></p>
  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%=participant.username%>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<%#= render "breadpart/breadcrumb" %>
<div class="messages-box">
  <div class="center-div">
    <% page_header "Your Conversations" %>
    <div class="row">
      <div class="col-sm-3">
        <ul class="nav nav-pills nav-stacked" id="msgmenu">
          <li><%= link_to 'Νέο', new_message_path%></li>
          <li class="active"><%= mailbox_section 'Inbox', @box %></li>
          <li><%= mailbox_section 'Sent', @box %></li>
          <li><%= mailbox_section 'Trash', @box %></li>
        </ul>
      </div>
      <div class="col-sm-9">
        <% if @box == 'trash' %>
          <p>
            <%= link_to 'Άδειασμα κάδου', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,data: {confirm: 'Are you sure?'} %>
          </p>
        <% end %>
        <%if @conversations.present? %>
          <ul class="list-group">
            <%= render partial: 'conversations/conversation', collection: @conversations %>
          </ul>
        <%else%>
          <h1 class= "glyphicon glyphicon-envelope"></h1>
          <h3>Κανένα μήνυμα!</h3>
        <%end%>
        <div class="center-div">
          <div class="digg_pagination">
            <%= will_paginate  :previous_label => '<', :next_label => '>' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="center-div">
  <div class="messages-box">
    <% page_header "Conversation" %>
    <p>Chatting with
     <%= render 'conversations/participants', conversation: @conversation %>
    </p>
    <div class="panel panel-default">
      <div class="panel-heading"><%= @conversation.subject %></div>
      <div class="panel-body">
        <div class="messages">
          <% @conversation.receipts_for(current_user).order(created_at: :desc).each do |receipt| %>
            <div class="msg">
              <p class="received-message"><% message = receipt.message %></p>
              <p class="sender-message"><span><%= message.sender.name %></span>
                <small class="pull-right"><span class="text-muted"><%= message.created_at.strftime("%-d %b %Y, %H:%M") %></span></small>
              </p>
              <p class="body-message"><%= simple_format(word_wrap(message.body , line_width: 80)) %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= form_tag reply_conversation_path(@conversation), method: :post do %>
      <div class="form-group" word-wrap="break-word">
        <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
      </div>
      <div class="linkbtn">
        <%= submit_tag "Αποστολή", class: 'btn-submit' %>
      </div>
    <% end %>
  </div>
</div>