config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  default_url_options host: 'localhost:3000'

  get '/contact', to: 'messages#contact'

  resources :record_libraries
  resources :friendships
  root 'albums#index'

  get 'sessions/new'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :messages, only: %i[new create]

  get 'admin/dashboard' => 'admin#index'
  # The namespace  creates a nested url for admin panel check rake routes for details
  namespace :admin do
    get 'categories/new' => 'categories#new_category'
    resources :categories, only: %i[index create edit update delete]

    get 'artists/new' => 'artists#new_artist'
    get 'artists' => 'artists#index_artist'
    get 'artists/:id/edit' => 'artists#edit_artist', as: 'artists_edit'
    resources :artists, only: %i[create update destroy]

    get 'albums/new' => 'albums#new_album'
    get 'albums' => 'albums#index_album'
    get 'albums/:id/edit' => 'albums#edit_album', as: 'albums_edit'
    resources :albums, only: %i[create update destroy]

    resources :photos
    get 'songs/new' => 'songs#new_song'
    get 'songs' => 'songs#index_song'
    get 'songs/:id/edit' => 'songs#edit_song', as: 'songs_edit'
    resources :songs, only: %i[index create edit update destroy]

    get 'bands/new' => 'bands#new_band'
    get 'bands' => 'bands#index_band'
    get 'bands/:id/edit' => 'bands#edit_band', as: 'bands_edit'
    resources :bands, only: %i[index create edit update destroy]

    get 'users/new' => 'users#new_user'
    get 'users' => 'users#index_user'
    get 'user/:id/edit' => 'users#user_edit', as: 'user_edit'
    resources :users, only: %i[create update destroy]
  end

  resources :bands
  resources :artists
  resources :recommendations, only: %i[index]
  get 'album/:id' => 'albums#show', as: 'album'

  # mailboxer
  resources :conversations, only: %i[index show destroy create] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
    member do
      post :mark_as_read
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  get 'categories' => 'categories#index'
  resources :categories
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships
  has_many :friends, through: :friendships
  has_one :user_vector
  has_one :music_recommendation
  # this is to be able to see followed by
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :record_libraries
  has_many :albums, through: :record_libraries

  accepts_nested_attributes_for :user_vector

  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 }

  validates :email, presence: true, length: { maximum: 255 },
                    # format: { with: VALID_EMAIL_REGEX },t
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  # Mailboxer
  acts_as_messageable

  def mailboxer_email(object)
    puts object
    email
end

  def name
    username
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(_tok)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :require_admin
  before_action :set_user, only: %i[update destroy]
  def index_user
    @users = User.all
  end

  def new_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to MusicDB!'
      redirect_to admin_users_url

    else
      render 'new'
    end
  end

  def user_edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Successfuly updated!'
      redirect_to admin_users_path
    else
      flash[:warning] = 'Pleae try again'
      redirect_to admin_user_edit_path
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'User Successfuly deleted'
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :is_admin, :remember_digest)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.includes(
      :record_libraries,
      [record_libraries: :user],
      :inverse_friends,
      :friendships,
      friendships: [:friend],
      albums: [:photos]
    ).find(params[:id])
  end

  def index
    @users = User.all.paginate(page: params[:page] || 1, per_page: 15)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # TODO: Use this to create needed vectors upon user creation
      unless @user.user_vector
        @user.user_vector = UserVector.new
        @user.save
      end
      unless @user.music_recommendation
        @user.music_recommendation = MusicRecommendation.new
        @user.save
      end
      log_in @user
      flash[:success] = 'Welcome to MusicDB!'
      redirect_to @user

    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Successfuly updated!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :is_admin, :remember_digest)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def users_for_select
    User.all
  end
end

app/views/users/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <ol class="breadcrumb">
        <li class="active">
          <i class="fa fa-dashboard"></i> Users
        </li>
      </ol>
      <%= render 'admin/flash_messages'%>
      <div class="panel panel-default">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th><%= link_to "New" , admin_users_new_path, class: "pull-right btn btn-success btn-md"%></th>
            </tr>
          </thead>
          <tbody>
            <%@users.each do |user|%>
              <%= render 'users/user_row', user: user%>
            <%end%>
          </tbody>
        </table>
      </div>

app/views/users/_register.html.erb
<div class="new-user">
  <h3>Sign Up</h3>
  <div class='row'>
    <div class='form-group'>
      <%=form_for(@user) do |user|%>
        <%= render 'shared/error_messages' %>
        <div id='register-form' class='col-xs-12 col-sm-12 col-md-12'>
          <%=user.text_field :username, placeholder: 'Username' , class: 'form-control'%>
        </div>
        <div id='register-form'  class='col-xs-12 col-sm-12 col-md-12'>
          <%=user.text_field :email, placeholder: 'email' , class: 'form-control'%>
        </div>
        <div id='register-form'  class='col-xs-12 col-sm-12 col-md-12'>
          <%=user.password_field :password, placeholder: 'Password' , class: 'form-control'%>
        </div>
        <div id='register-form'  class='col-xs-12 col-sm-12 col-md-12'>
          <%=user.password_field :password_confirmation, placeholder: 'Password Confirmation' , class: 'form-control'%>
        </div>
        <div id='register-form'  class='col-xs-12 col-sm-12 col-md-12'>
          <%=user.submit 'Sign Up' , class: 'btn btn-primary btn-block'%>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/users/_user_fields.html.erb
<div class='row'>
  <div class='form-group'>
    <%=form_for@user,html: {role: "form" ,'data-toggle' => "validator"} do |user|%>
      <%= render 'shared/error_messages' %>
      <div id='register-form' class='col-xs-12 col-sm-12 col-md-12'>
        <div class="form-group">
          <label for="inputEmail">Email</label>
          <%=user.text_field :username, placeholder: 'Username' , class: 'form-control', :required => true%>
        </div>
      </div>
      <div id='register-form'  class='col-xs-12 col-sm-12 col-md-12'>
        <div class="form-group">
          <label for="inputEmail">Email</label>
          <%=user.text_field :email,class: "form-control", placeholder: 'email' ,id:"inputEmail",type: 'email' ,'data-error' =>"That email address is invalid",:required => true%>
          <div class="help-block with-errors"></div>
        </div>
      </div>
      <div id='register-form'  class='col-xs-12 col-sm-12 col-md-12'>
        <label for="inputPassword">Password</label>
        <div class="form-group">
          <%=user.password_field :password, placeholder: 'Password' ,id: "inputPassword", class: 'form-control','data-minlength' => "6",:required => true%>
          <div class="help-block with-errors"></div>
        </div>
      </div>
      <div id='register-form'  class='col-xs-12 col-sm-12 col-md-12'>
        <div class="form-group">
          <label for="inputPasswordConfirmation">Password Confirmation</label>
          <%=user.password_field :password_confirmation, placeholder: 'Password Confirmation' ,id: "inputPasswordConfirmation", class: 'form-control','data-minlength' => "6", :required => true%>
          <div class="help-block with-errors"></div>
        </div>
      </div>
      <div id='register-form'  class='col-xs-12 col-sm-12 col-md-12'>
        <%=user.submit 'Sign Up' , class: 'btn btn-primary btn-block'%>
      </div>
    <%end%>
  </div>
</div>

app/views/users/_user_row.html.erb
<tr>
  <td><%=user.username%></td>
  <td>
    <%=user.email%>
  </td>
  <td>
    <%= link_to admin_user_edit_path(user),class: "btn btn-primary btn-xs pull-right" do %>
      <span class="glyphicon glyphicon-edit"></span>Edit</button>
  <%end%>
  <%= link_to admin_user_path(user),method: :delete, data: {confirm: 'Are you sure?'},class: "btn btn-danger btn-xs pull-right" do %>
    <span class="glyphicon glyphicon-remove-circle"></span> Delete</button>
<%end%>
</td>
</tr>

app/views/users/edit.html.erb
<div class="edit-user">
  <div class='container'>
    <h3>Edit Profile</h3>
    <%=render 'user_fields'%>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Name</th>
        <th scope="col">Follow</th>
      </tr>
    </thead>
    <tbody>
      <%@users.each do |user|%>
        <tr>
          <td><%=user.id%></td>
          <td><%=link_to user.name , user_path(user)%></td>
          <%unless current_user.friendships.collect(&:friend_id).include?(user.id)%>
            <td><%=link_to 'Follow',friendships_path(:friend_id => user.id),:type=> "button",:class => "btn btn-success", :method => :post%></td>
          <%else%>
            <td><%=link_to "UnFollow", friendships_path(:friend_id => user.id),:type=> "button",:class => "btn btn-danger", :method => :delete%></td>
          <%end%>
        </tr>
      <%end%>
    </tbody>
  </table>
  <%= will_paginate @users , :previous_label => '<', :next_label => '>' %>
</div>

app/views/users/new.html.erb
<div class='container'>
  <%=render 'register'%>
</div>

app/views/users/show.html.erb
<div class='container'>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Record Library</a></li>
    <li><a data-toggle="tab" href="#menu1">Followers</a></li>
    <li><a data-toggle="tab" href="#menu2">Following</a></li>
    <li><a data-toggle="tab" href="#menu3">User</a></li>
    <% if current_user %>
      <li><%= link_to 'Your Conversations', conversations_path %></li>
    <%end%>
  </ul>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="tab-content">
    <div id="menu3" class="tab-pane fade">
      <div class="row">
        <div class="col-md-3">
          <table class="table table-sm table-dark">
            <tbody>
              <tr>
                <td>Username:</td>
                <td><%=@user.username%></td>
              </tr>
              <tr>
                <td>Email:</td>
                <td><%= @user.email%></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div id="menu1" class="tab-pane fade">
      <div class="row">
        <div class="col-md-4 col-md-offset-1 ">
          <h3>Following</h3>
          <table class="table table-sm table-dark">
            <tbody>
              <%@user.friendships.each do |friendship|%>
                <tr>
                  <td><%=friendship.friend.username%> </td>
                  <td><%=link_to "UnFollow", friendship ,:type=> "button",:class => "btn btn-danger", :method => :delete%></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div id="menu2" class="tab-pane fade">
      <div class="row">
        <div class="col-md-2 col-md-offset-1 ">
          <h3>Followed by</h3>
          <table class="table table-sm table-dark">
            <tbody>
              <% @user.inverse_friends.each do |inverse_friend|%>
                <tr>
                  <td><%= inverse_friend.username%></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div id="home" class="tab-pane active ">
      <h1>Record Library</h1>
      <%if  current_user%>
        <%@user.albums.each do |album|%>
          <%= render 'albums/local_index', album: album , user: @user%>
        <%end%>
      <%else%>
        <h3>Please log in</h3>
        <%=link_to 'Login',login_path%>
      <%end%>
    </div>
  </div>
</div>