config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  default_url_options host: 'localhost:3000'

  get '/contact', to: 'messages#contact'

  resources :record_libraries
  resources :friendships
  root 'albums#index'

  get 'sessions/new'
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :messages, only: %i[new create]

  get 'admin/dashboard' => 'admin#index'
  # The namespace  creates a nested url for admin panel check rake routes for details
  namespace :admin do
    get 'categories/new' => 'categories#new_category'
    resources :categories, only: %i[index create edit update delete]

    get 'artists/new' => 'artists#new_artist'
    get 'artists' => 'artists#index_artist'
    get 'artists/:id/edit' => 'artists#edit_artist', as: 'artists_edit'
    resources :artists, only: %i[create update destroy]

    get 'albums/new' => 'albums#new_album'
    get 'albums' => 'albums#index_album'
    get 'albums/:id/edit' => 'albums#edit_album', as: 'albums_edit'
    resources :albums, only: %i[create update destroy]

    resources :photos
    get 'songs/new' => 'songs#new_song'
    get 'songs' => 'songs#index_song'
    get 'songs/:id/edit' => 'songs#edit_song', as: 'songs_edit'
    resources :songs, only: %i[index create edit update destroy]

    get 'bands/new' => 'bands#new_band'
    get 'bands' => 'bands#index_band'
    get 'bands/:id/edit' => 'bands#edit_band', as: 'bands_edit'
    resources :bands, only: %i[index create edit update destroy]

    get 'users/new' => 'users#new_user'
    get 'users' => 'users#index_user'
    get 'user/:id/edit' => 'users#user_edit', as: 'user_edit'
    resources :users, only: %i[create update destroy]
  end

  resources :bands
  resources :artists
  resources :recommendations, only: %i[index]
  get 'album/:id' => 'albums#show', as: 'album'

  # mailboxer
  resources :conversations, only: %i[index show destroy create] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
    member do
      post :mark_as_read
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  get 'categories' => 'categories#index'
  resources :categories
end

app/models/band.rb
class Band < ApplicationRecord
  searchkick word_start: [:name]
  has_many :albums, dependent: :nullify
  # has_many :songs
  has_many :bandmembers, dependent: :destroy
  has_many :photos, as: :imageable, dependent: :destroy
  has_many :artists, through: :bandmembers
  belongs_to :category, optional: true

  validates :name, presence: true
  # validates :artist_id, presence: true
  validates :category_id, presence: true
  # validates :photos, presence: true

  def search_data
    {
      name: name
    }.merge(search_albums)
  end

  def search_albums
    {
      album_names: albums.map(&:name)
    }
  end
end
# Band.reindex

app/controllers/admin/bands_controller.rb
class Admin::BandsController < AdminController
  before_action :require_admin
  before_action :set_band, only: %i[update destroy]
  def index_band
    @bands = Band.includes([:category])
  end

  def new_band
    @band = Band.new
    @artists = Artist.all.map { |x| [x.name.to_s, x.id.to_s] }
  end

  def create
    @band = Band.new(band_params)
    if @band.save!
      # byebug
      if params[:band][:artists]
        params[:band][:artists].each do |artist|
          @bandmembers = @band.bandmembers.build(artist_id: artist) # unless artist.empty?
          @bandmembers.save # unless artist.empty?
          ## byebug
        end
      end
      if params[:images]
        params[:images].each do |image|
          @band.photos.create(image: image)
        end
      else
        @band.photos.create
      end
      flash[:success] = "Band #{@band.name} is created"
      redirect_to admin_bands_path
    else
      flash[:warning] = 'Please try again'
      redirect_to admin_bands_new_path
    end
  end

  def edit_band
    @band = Band.find(params[:id])
    @artists = Artist.all.map { |x| [x.name.to_s, x.id.to_s] }

    @count = Bandmember.where(band_id: @band.id)
    # byebug
    @array = []
    if @count.size > 1
      @count.each do |artist|
        @artist = Artist.find(artist.artist_id).id
        @array << @artist
      end
    elsif @count.size == 1
      @count = Bandmember.find_by(band_id: @band.id)
      @artist = Artist.find(@count.artist_id).id
      @array << @artist
    else
      @array = ['']
     end
     # @array = [""]
     # byebug
   end
  # @selected_artists = @array.map{|x| ["#{x.name}" ,"#{x.id}"]}

  def update
    # byebug
    if @band.update_attributes(band_params)
      if params[:band][:artists]
        params[:band][:artists].each do |artist|
          @bandmembers = @band.bandmembers.build(artist_id: artist) # unless artist.empty?
          @bandmembers.save # unless artist.empty?
          ## byebug
        end
      end
      flash[:success] = 'good'
      redirect_to admin_bands_edit_path
    end
  end

  def destroy
    @band.destroy
    redirect_to admin_bands_path
  end

  private

  def set_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name, :genre, :description, :artist, :photos, :category_id, artists: [:id]) # ,bandmember:[:band_id,:artist_id])
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action do
    @discogs = Discogs::Wrapper.new("Test OAuth", user_token: 'uUAcpNNqtCmvrLITnpzKeuxfUcxsQdeGRJRggXqq')
  end


  def show
    @band = Band.find(params[:id])
    @result =  @discogs.search(@band.name.to_s, :per_page => 10, :type => :artist)
    @band_discogs = @discogs.get_artist(@result.results.first.id.to_s)

  end
end

app/helpers/bands_helper.rb
module BandsHelper
  def bands_for_select
    Band.all.collect { |u| [u.name.to_s, u.id] }
  end
end

app/views/bands/_band_row.html.erb
<tr>
  <td><%=band.name%></td>
  <td><%=band.category.name%></td>
  <td>
    <%= link_to admin_bands_edit_path(band),class: "btn btn-primary btn-xs pull-right" do %>
      <span class="glyphicon glyphicon-edit"></span>Edit</button>
  <%end%>
  <%= link_to admin_band_path(band),method: :delete, data: {confirm: 'Are you sure?'},class: "btn btn-danger btn-xs pull-right" do %>
    <span class="glyphicon glyphicon-remove-circle"></span> Delete</button>
<%end%>
</td>
</tr>

app/views/bands/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <ol class="breadcrumb">
        <li class="active">
          <i class="fa fa-dashboard"></i> Album
        </li>
      </ol>
      <%= render 'admin/flash_messages'%>
      <div class="panel panel-default">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Category/Genre</th>
              <th><%= link_to "New" , admin_bands_new_path, class: "pull-right btn btn-success btn-md"%></th>
            </tr>
          </thead>
          <tbody>
            <%@bands.each do |band|%>
              <%= render 'bands/band_row', band: band%>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/bands/_local_index.html.erb
<li class="list-group-item">
  <%=link_to band.name, band_path(band)%>
</li>

app/views/bands/_new.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Dashboard <small>New Band</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <i class="fa fa-dashboard"></i> Band
          </li>
        </ol>
        <%= render 'admin/flash_messages'%>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= form_for [:admin,@band], :html => { :multipart => true } do |f| %>
          <% if @band.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@band.errors.count, "error") %> prohibited
                this seminars from being saved:
              </h2>
              <ul>
                <%@band.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="inputName"  class='pull-left'>Name</label>
            <%= f.text_field :name, class: "form-control",id: 'inputName' , :required => true %>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label for="artist"  class='pull-left'>Choose Artists</label>
            <%=f.select(:artists, options_from_collection_for_select(Artist.all, :id,:name, @array),{}, {multiple: true ,class: 'form-control select2', id: 'artist', :required => true}) %>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label for="artist"  class='pull-left'>Category/Genre</label>
            <%= f.select(:category_id, deep_categories_for_select, {include_blank:true , include_hidden:false}  , class: 'select2 form-control', :required => true)%>
            <div class="help-block with-errors"></div>
          </div>
          <% if @band.photos.exists? %>
            <% @band.photos.each do |z| %>
              <div class="seminarimage">
                <% if !z.image_file_size.nil? %>
                  <%= image_tag z.image , class: "showimage" %>
                  <%= link_to "Delete Photo",admin_photo_path(z), :method => :delete  , remote: true , class: "photo_delete"%>
                <%else%>
                  <p>
                    Προσθέστε μια φωτογραφία
                  </p>
                <%end%>
              </div>
            <%end%>
          <%end%>
          <div class="control-group">
            <%= f.label :photos, :class => 'control-label' %>
            <div class="form-group">
              <%= file_field_tag "images[]", type: :file, multiple: true ,class: "form-control-file" %>
            </div>
          </div>
          <p>
            <%= f.submit nil , class: 'btn btn-primary' %>
          </p>
        <% end %>
        <%= link_to 'Back', admin_dashboard_path %>
      </div>
    </div>
  </div>
</div>

app/views/bands/show.html.erb
<div class ="container">
  <div class = "row">
    <div class="col-md-4">
      <%=@band.name%>
    </div>
    <div class="col-md-4">
      <%=@band_discogs.profile%>
    </div>
  </div>
  <div class="row">
    <h1>Albums</h1>
  </div>
  <div class="row">
    <%@band.albums.each do |album|%>
      <%= render 'albums/local_index', album: album%>
    <%end%>
  </div>
</div>